apiVersion: v1
kind: Service
metadata:
  name: task-api-service
  namespace: taskmanager
spec:
  type: NodePort
  selector:
    app: task-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
